# curl -X POST \
# -H "Accept: application/vnd.github+json"\
# -H "Authorization: token{personal token with repo access}"\
# -d '{"event_type": "webhook", "client_payload":{"key":"value"}}'\
# https://api.github.com/repos/{owner}/{repo}/dispatches

name: "Webhook Event example"

on:
  repository_dispatch:
    types:
      - webhook

jobs:
  respond-to-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Run a script
        run: |
        echo "Event of type: $GITHUB_EVENT_NAME"