- name: Test ansible in github
  hosts: localhost
  gather_facts: true # Ensures ansible_user is available
  vars:
    ansible_connection: local  # Forces Ansible to run locally without SSH

  roles:
    - role: common