name: VPC destroy terraform
on: [workflow_dispatch]
jobs: 
  DESTROY:
    runs-on: self-hosted
    steps:
      - name: checkout code
        uses: actions/checkout@v4 
        with: 
          fetch-depth: 0
          sparse-checkout: vpc
          sparse-checkout-cone-mode: false
      - name: destroy terrafrom
        run: |
          cd vpc; terraform destroy -auto-approve