name: Retrive vault secrets
# store vault token in github VAULT_TOKEN
on: [workflow_dispatch]
jobs:
  Vault: 
    runs-on: self-hosted
    steps:
      - name: Import secrets
        id: import-secrets
        uses: hashicorp/vault-action@v2
        with:
          url: https://vault.test.online:8200
          token: ${{secrets.VAULT_TOKEN}}
          tlsSkipVerify: true
          secrets: |
            kv/data/test MYPASS | mypass; 
          #storing it under MYPASS-> mypass in env
      - run: env 


      # usage {{env.VARIABLE}}
