name: Self hosted test
run-name: ${{ github.actor }} - ${{ github.event.head_commit.message }}
on: [push,workflow_dispatch]
jobs:
  DEV:
    runs-on: self-hosted
    steps:
      - run: |
          pwd
          hostname
          ls
          ip a
          echo hello
          echo success