name: | 
  github actions revice 
run-name: ${{github.actor}}
on:
  push:

jobs:
  DEV:
    runs-on: ubuntu-latest
    steps:
      - name: test name
        run: echo manu ok test
  
  PROD:
    needs:
      - DEV
    runs-on: ubuntu-latest
    steps:
      - name: Prod check
        run: echo production run ok