name: Learn github actions
run-name: ${{ github.actor }} - ${{ github.event.head_commit.message }}
on: [push,workflow_dispatch] # list
jobs:
  DEV: #dev environment
    runs-on: ubuntu-latest
    steps:
         - run: echo Hello

  QA: #QA dummy environment
    runs-on: ubuntu-latest
    needs:
         - DEV
    steps:
         - run: echo Hello

  UAT: #uat dummy environment
    runs-on: ubuntu-latest
    needs:
         - QA
    steps:
         - run: echo Hello

  PROD: #prod environment
    runs-on: ubuntu-latest
    needs:
         - UAT
    steps:
         - run: echo Hello    
     
