name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push] # list
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
         - uses: actions/checkout@v4
         - run: echo Hello 
     
